name: "Prepare package"
on: [push]
jobs:
  buildPackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Run the Maven package command
        run: mvn test -DskipTests package
      - run: ls target/
      - run: mv target/*.jar app.jar
      - uses: ncipollo/release action@v4
        with:
          artifacts: "target/*.jar"
          body: "My release of version: ${{github.ref}}"
